name: Generate plugin archive for new release
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Install dependencies
      run: npm install
    - name: Build 
      run: npm run build
    - name: Run Unit tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test
    - name: Get current package version
      id: package_version
      uses: martinbeentjes/npm-get-version-action@v1.1.0
    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name : ${{ steps.package_version.outputs.current-version}}
        release_name: ${{ steps.package_version.outputs.current-version}}
        body: Release ${{ steps.package_version.outputs.current-version}}